#!/usr/bin/env python3
# Build distribution archive for RISC OS version

from pathlib import Path
import subprocess

# Remove any existing levels
subprocess.check_call(["rm", "--force", "!WinColl/Level*,ffd"])

# Convert levels
for l in Path("wincoll/levels").glob("*.tmx"):
    subprocess.check_call(["./tiled2level", l, Path("!WinColl") / f"{l.stem},ffd"])

# Build Zip
subprocess.check_call(["mkdir", "-p", "dist"])
subprocess.check_call(["zip", "--recurse-paths", "dist/wincoll-riscos.zip", "!WinColl"])
