#!/usr/bin/env python3
# Build distribution archive for RISC OS version

import subprocess
from pathlib import Path


# Remove any existing levels
subprocess.check_call(["rm", "--force", "!WinColl/Level*,ffd"])

# Convert levels
for line in Path("wincoll/levels").glob("*.tmx"):
    subprocess.check_call(["./tiled2riscos", line, Path("!WinColl") / f"Level{line.stem},ffd"])

# Build Zip
subprocess.check_call(["mkdir", "-p", "dist"])
subprocess.check_call(["zip", "--recurse-paths", "dist/wincoll-riscos.zip", "!WinColl"])
