#!/usr/bin/env python3
#
# © Reuben Thomas <rrt@sc3d.org> 2024
# Released under the GPL version 3, or (at your option) any later version.

import sys
import argparse
import warnings
from warnings import warn
from typing import NoReturn

import pytmx

# Command-line arguments
parser = argparse.ArgumentParser(
    description="Convert Tiled levels to WinColl plain text WinColl format.",
)
parser.add_argument("-V", "--version", action="version",
                    version="%(prog)s 0.1 (05 Dec 2024) by Reuben Thomas <rrt@sc3d.org>")
parser.add_argument("tiled_file", metavar="TILED-MAP", help="Tiled map output file")
parser.add_argument("wincoll_file", metavar="WINCOLL-LEVEL", help="plain text WinColl level file")
args = parser.parse_args()

# Error messages
def simple_warning(message, category, filename, lineno, file, line):  # type: ignore, pylint: disable=unused-argument, too-many-arguments, too-many-positional-arguments
    print(f"{parser.prog}: {message}", file=file or sys.stderr)

warnings.showwarning = simple_warning  # type: ignore

def die(code: int, msg: str) -> NoReturn:
    warn(msg)
    sys.exit(code)


# Read the input and convert tile GIDs to text
tiled_map = pytmx.TiledMap(args.tiled_file)

gid_to_char = {
    "32.png": " ",
    "35.png": "#",
    "36.png": "$",
    "42.png": "*",
    "43.png": "+",
    "46.png": ".",
    "64.png": "@",
    "75.png": "K",
    "87.png": "W",
}
lines = []
text = ""
for tile in tiled_map.get_layer_by_name("Tile Layer 1").tiles():
    text += gid_to_char[tile[2][0]]

# Convert tile string to lines and save it
level_size = 50
output = "\n".join(
    [text[i:i + level_size] for i in range(0, len(text), level_size)],
) + "\n"
with open(args.wincoll_file, "w", encoding="utf-8") as fh:
    fh.write(output)
